CREATE TABLE person
(
    id   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    age  INTEGER CHECK ( age < 100 )
);

CREATE TABLE passport
(
    person_id       INTEGER PRIMARY KEY REFERENCES person (id) ON DELETE CASCADE,
    passport_number INTEGER NOT NULL
);

INSERT INTO person(name, age)
VALUES ('Tom', 35),
       ('Bob', 52),
       ('Katy', 14);

INSERT INTO passport (person_id, passport_number)
VALUES ((select id from person where name = 'Tom'),),
       ((select id from person where name = 'Tom'), 'AirPods'),
       (2, 'Iphone'),
       (3, 'Kindle'),
       (3, 'TV'),
       (3, 'PlayStation');

SELECT *
FROM person;

SELECT *
FROM passport;



TRUNCATE passport;

ALTER TABLE passport
    DISABLE TRIGGER ALL;

TRUNCATE person CASCADE;

ALTER TABLE passport
    ENABLE TRIGGER ALL;

SELECT pn.name, pn.age, pt.passport_number
FROM person pn
         JOIN passport pt ON pn.id = pt.person_id

