create database first_db;

CREATE TABLE person
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR NOT NULL,
    age     INTEGER NOT NULL CHECK ( age > 0 ),
    email   VARCHAR NOT NULL UNIQUE

);

INSERT INTO person(name, age, email)
VALUES ('Иван Иванов Иванович',  30, 'ivan@gmail.com'),
       ('Петров Петр Петрович',  50, 'petr@gmail.com'),
       ('Лебедев Артем Иванович',  25, 'artem@gmail.com'),
       ('Федеров Мирон Янович ',  38, 'miron@gmail.com');

SELECT *
FROM person;

DROP table person;



