create database first_db;

CREATE TABLE person
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR NOT NULL,
    surname VARCHAR NOT NULL,
    age     INTEGER NOT NULL CHECK ( age > 0 ),
    email   VARCHAR NOT NULL UNIQUE
);

INSERT INTO person(name, surname, age, email,address)
VALUES ('Zaur', 'Babayev', 37, 'zaur@gmail.com','Baki'),
       ('Vusal', 'Kerimov', 30, 'vusal@gmail.com','Nuxa'),
       ('Nagi', 'Nagiyev', 23, 'nagi@gmail.com','Gence'),
       ('Kamil', 'Eliyev', 54, 'kamil@gmail.com','Tovuz');

SELECT *
FROM person;

DROP table public.person;

delete
from person
where id = 5;

truncate person;

alter table person add column address VARCHAR NOT NULL;

UPDATE person SET address='England, London, 234567';

