CREATE TABLE person
(
    id   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    age  INTEGER CHECK ( age < 100 )
);

CREATE TABLE passport
(
    id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    passport_number INTEGER NOT NULL,
    person_id       INTEGER UNIQUE REFERENCES person (id) ON DELETE CASCADE
);


SELECT *
FROM person;

SELECT *
FROM passport;


TRUNCATE passport;

ALTER TABLE passport
    DISABLE TRIGGER ALL;

TRUNCATE person CASCADE;

ALTER TABLE passport
    ENABLE TRIGGER ALL;

SELECT pn.name, pn.age, pt.passport_number
FROM person pn
         JOIN passport pt ON pn.id = pt.person_id;


drop table passport;

DROP TABLE person;