create database first_db;

CREATE TABLE person
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(100)                               NOT NULL,
    year_of_birth date CHECK ( year_of_birth > '1900-01-01') NOT NULL
);

INSERT INTO person(full_name, year_of_birth)
VALUES ('Иван Иванов Иванович', '1990-03-05'),
       ('Петров Петр Петрович', '1970-07-23'),
       ('Лебедев Артем Иванович', '1980-03-25'),
       ('Федеров Мирон Янович ', '1950-04-04');


CREATE TABLE book
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     VARCHAR(100) NOT NULL,
    author    VARCHAR(100) NOT NULL,
    year      INTEGER      NOT NULL,
    person_id INTEGER      REFERENCES person (id) ON DELETE SET NULL
);

INSERT INTO book(title, author, year, person_id)
VALUES ('Чистый код', ' Роберт Мартин', 2000, 1),
       ('Совершенный код', 'Стив Макконнелл', 1990, 2),
       ('Программист-прагматик. Путь от подмастерья к мастеру', 'Эндрю Хант и Дэвид Томас', 2001, 2),
       ('Эффективная работа с унаследованным кодом', 'Майкл Физерс', 1998, 4);


SELECT *
FROM person;

DROP table person;
DROP table book;



