CREATE TABLE person
(
    id   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    age  INTEGER CHECK ( age < 100 )
);

CREATE TABLE item
(
    id        INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    person_id INTEGER      REFERENCES person (id) ON DELETE SET NULL,
    item_name VARCHAR(100) NOT NULL
);

INSERT INTO person(name, age)
VALUES ('Tom', 35),
       ('Bob', 52),
       ('Katy', 14);

INSERT INTO item (person_id, item_name)
VALUES ((select id from person where name = 'Tom'), 'Book'),
       ((select id from person where name = 'Tom'), 'AirPods'),
       (2, 'Iphone'),
       (3, 'Kindle'),
       (3, 'TV'),
       (3, 'PlayStation');

SELECT *
FROM person;

SELECT *
FROM item;

SELECT p.name, p.age, i.item_name
FROM person p
         JOIN item i ON p.id = i.person_id;

