create table person
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    age  INTEGER      NOT NULL
);

INSERT INTO person (name, age)
VALUES ('Tom',20),
       ('Bob',23),
       ('Toni',30);

ALTER TABLE person ADD COLUMN email VARCHAR(100) UNIQUE ;