CREATE SCHEMA cascade_example;

drop table person;

drop table "order";

CREATE TABLE person
(
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(100) NOT NULL,
    age     INTEGER
);

CREATE TABLE "order"
(
    order_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   INTEGER REFERENCES person (user_id) ON DELETE SET NULL ,
    item_name VARCHAR(100)
);

INSERT INTO person (name, age)
VALUES ('Tom', 30);

INSERT INTO "order" (user_id, item_name)
VALUES ((SELECT user_id FROM person WHERE name = 'Tom'), 'Iphone');

SELECT *
FROM person;

SELECT *
FROM "order";



DELETE
FROM person
WHERE user_id = 1;

