CREATE SCHEMA many_to_many;

CREATE TABlE actor
(
    actor_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(100) NOT NULL UNIQUE,
    age      INT CHECK ( age > 0 )
);

-- one_to_many schema daxilində olan movie cədvəlindən istifadə edəcəyik.

INSERT INTO actor (name, age)
VALUES ('Harvey Keitel', 81),
       ('Robert De Niro', 77),
       ('Leonardo DiCaprie', 46),
       ('Jason Statham', 53),
       ('Joe Pesci', 77),
       ('Samuel L. Jackson', 72);

SELECT *
FROM actor;

select *
from one_to_many.movie;

CREATE TABLE actor_movie
(
    actor_id INT REFERENCES actor (actor_id),
    movie_id INT REFERENCES one_to_many.movie (movie_id),
    PRIMARY KEY (movie_id, actor_id)
);

INSERT INTO actor_movie (actor_id, movie_id)
VALUES (1, 1),
       (1, 2),
       (2, 5),
       (2, 6),
       (3, 4),
       (3, 7),
       (3, 11),
       (4, 8),
       (4, 9),
       (5, 6),
       (6, 2),
       (6, 3);


SELECT a.name actor_name, m.name movie_name
FROM actor a
         JOIN actor_movie am ON a.actor_id = am.actor_id
         JOIN one_to_many.movie m ON am.movie_id = m.movie_id;
