CREATE SCHEMA one_to_one;

CREATE TABLE citizen
(
    citizen_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    age        INT CHECK ( age > 0 )
);

CREATE TABLE passport
(
    citizen_id      INT PRIMARY KEY REFERENCES citizen (citizen_id),
    passport_number INT NOT NULL
);

INSERT INTO citizen(name, age)
VALUES ('Bob', 12),
       ('Tom', 24),
       ('Katy', 39),
       ('Alice', 45);


INSERT INTO passport(citizen_id, passport_number)
VALUES (1, 12345),
       (2, 75124),
       (3, 91245),
       (4, 19259);

select *
from citizen;

select *
from passport;

SELECT c.name, c.age, p.passport_number
FROM citizen c
         JOIN passport p ON c.citizen_id = p.citizen_id;


SELECT c.name, p.passport_number
FROM citizen c
         CROSS JOIN passport p;

